name: cinemax
description: A Flutter movie app.


publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  http: ^0.13.4
  webview_flutter: ^3.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.18
  flutter_inappwebview: ^5.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: PoppinsSB
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
  
flutter_native_splash:
  color: "#252625"
  image: assets/images/logo.png
